// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: protos/foo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Idade         int64                  `protobuf:"varint,2,opt,name=idade,proto3" json:"idade,omitempty"`
	IsBrazilian   bool                   `protobuf:"varint,3,opt,name=is_brazilian,json=isBrazilian,proto3" json:"is_brazilian,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_protos_foo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_foo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_protos_foo_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SayHelloRequest) GetIdade() int64 {
	if x != nil {
		return x.Idade
	}
	return 0
}

func (x *SayHelloRequest) GetIsBrazilian() bool {
	if x != nil {
		return x.IsBrazilian
	}
	return false
}

type SayHellorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHellorResponse) Reset() {
	*x = SayHellorResponse{}
	mi := &file_protos_foo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHellorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHellorResponse) ProtoMessage() {}

func (x *SayHellorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_foo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHellorResponse.ProtoReflect.Descriptor instead.
func (*SayHellorResponse) Descriptor() ([]byte, []int) {
	return file_protos_foo_proto_rawDescGZIP(), []int{1}
}

func (x *SayHellorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_foo_proto protoreflect.FileDescriptor

const file_protos_foo_proto_rawDesc = "" +
	"\n" +
	"\x10protos/foo.proto\x12\thelloword\"^\n" +
	"\x0fSayHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05idade\x18\x02 \x01(\x03R\x05idade\x12!\n" +
	"\fis_brazilian\x18\x03 \x01(\bR\visBrazilian\"-\n" +
	"\x11SayHellorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2O\n" +
	"\aGreeter\x12D\n" +
	"\bSayHello\x12\x1a.helloword.SayHelloRequest\x1a\x1c.helloword.SayHellorResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_protos_foo_proto_rawDescOnce sync.Once
	file_protos_foo_proto_rawDescData []byte
)

func file_protos_foo_proto_rawDescGZIP() []byte {
	file_protos_foo_proto_rawDescOnce.Do(func() {
		file_protos_foo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_foo_proto_rawDesc), len(file_protos_foo_proto_rawDesc)))
	})
	return file_protos_foo_proto_rawDescData
}

var file_protos_foo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_foo_proto_goTypes = []any{
	(*SayHelloRequest)(nil),   // 0: helloword.SayHelloRequest
	(*SayHellorResponse)(nil), // 1: helloword.SayHellorResponse
}
var file_protos_foo_proto_depIdxs = []int32{
	0, // 0: helloword.Greeter.SayHello:input_type -> helloword.SayHelloRequest
	1, // 1: helloword.Greeter.SayHello:output_type -> helloword.SayHellorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_foo_proto_init() }
func file_protos_foo_proto_init() {
	if File_protos_foo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_foo_proto_rawDesc), len(file_protos_foo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_foo_proto_goTypes,
		DependencyIndexes: file_protos_foo_proto_depIdxs,
		MessageInfos:      file_protos_foo_proto_msgTypes,
	}.Build()
	File_protos_foo_proto = out.File
	file_protos_foo_proto_goTypes = nil
	file_protos_foo_proto_depIdxs = nil
}
